#ifndef VERTCOIN_CRYPTO_VERTHASH_CONSTANTS_H
#define VERTCOIN_CRYPTO_VERTHASH_CONSTANTS_H

#define VERTHASH_MULTIPLICATION 32        // 1024/32-1
#define VERTHASH_ROW_INITIALIZATION_VALUE 0x1000193
#define VERTHASH_SEEK_SET 73728
#define CHUNK_SIZE 1048576
#define HASH_CHUNK_SIZE 256
#define CHUNK_COUNT 1024
#define DATAFILE_INTERVAL_BLOCKS 1000
#define DATAFILE_INTERVAL_OVERLAP 100

#endif // VERTCOIN_CRYPTO_VERTHASH_CONSTANTS_H
